development:
  adapter: postgresql
  encoding: unicode
  database: handsome_development
  pool: 5
  username: maks
  password: 3322

test:
  adapter: postgresql
  encoding: unicode
  database: handsome_test
  pool: 5
  username: maks
  password: 3322